sonar.projectKey=travel-etl
sonar.projectName=Travel ETL

sonar.sources=cron_app
sonar.tests=cron_app/tests

sonar.exclusions=cron_app/tests/**

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8